### ISSUE TITLE
Can you release a new datset from the Sun RGB-D datase, which is used in this work ?

### ISSUE THREAD

**Issue by HCMSwang** [proteus1991/GridDehazeNet#10]
Thanks for share the code. This work is very great. In your work, you collect a new datset from the Sun RGB-D dataset, can you release this new dataset ?

**Comment by proteus1991** [comment]
Hi, the Sun RGB-D dataset is not specific for image dehazing, where only depth maps were used in our paper. We generated hazy images according to these depth maps in terms of the given hyper-parameters. Since we are not the authors of the original dataset, we consider not releasing the generated one.

**Comment by HCMSwang** [comment]
Thans for you help.

**Comment by HCMSwang** [comment]
Thanks for your help.
